ARG version
FROM almalinux:${version:-9}
ARG company="N2" \
    founder="Prasanna" \
    vision="Do Your Work It Will Give Better Results"
ENV company=${company} \
    founder=${founder} \
    vision=${vision}
RUN echo "Company is:${company}, Founder is :${founder}, Vision is :${vision}"