ARG version
FROM almalinux:${version:-9}
ARG company="N2" \
    founder="Prasanna" \
    vision="Do Your Work It Will Give Better Results"
RUN echo "Company is:${company}, Founder is :${founder}, Vision is :${vision}"